### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by bostjan** [angrychimp/php-dkim#5]
Hi Angry Chimp :)

There is no LICENSE file present in this repository. Would you decide on the license and add it to the repo, so the rest of the world knows what to expect? :)

Good sw otherwise, seems to work with minor hiccups.

Tnx,
b.

**Comment by angrychimp** [comment]
Sorry for the massive delay. This issue is resolved via 
dc4be39c6e01ae1cd705da644ea9c54237ac096b

**Comment by bostjan** [comment]
Tnx!

b.

**Comment by bostjan** [comment]
Two side notes:
1. You should add your license to composer.json

2. Feel free to cherry-pick changes from my repo:
https://github.com/teonsystems/php-dkim
(changes are done on teon-master branch)

Best regards,
b.
